### ISSUE TITLE
Use of podspec in new environment spec

### ISSUE THREAD

**Issue by cerebrate** [fission/docs.fission.io#277]
It used to be possible to apply certain modifications (specifically, in this case, nodeSelector clauses - being able to use those is essential in mixed-architecture clusters to ensure that correct binary images and functions are supplied to each node, or in clusters where functions require particular peripheral hardware not present on all nodes) to the builder and runtime pods created by fission, in this format:

```
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: binary-amd64
  namespace: default
spec:
  builder:
    command: build
    image: fission/binary-builder:v1.11.2
    podspec:
      nodeSelector:
        kubernetes.io/arch: amd64
  imagepullsecret: ""
  keeparchive: false
  poolsize: 1
  resources: {}
  runtime:
    image: fission/binary-env:1.11.2
    podspec:
      nodeSelector:
        kubernetes.io/arch: amd64
  version: 3
```

But now doing so fails, since the `containers:` element is mandatory in the new Environment CRD. Unfortunately, while this much is discoverable from the documentation at https://doc.crds.dev/github.com/fission/fission/fission.io/Environment/v1 , it's not at all obvious how to use the podspec clause (and its new mandatory element) to achieve what the above used to, or indeed to get a working spec at all. (I have not yet managed it.)

Could we have an example showing how to use podspec, and possibly also some common usages of it in the primary documentation?
